#!/bin/bash
sudo useradd jenkins
sudo runuser -l jenkins -c 'mkdir .ssh'
sudo runuser -l jenkins -c 'chmod -R 700 .ssh'
sudo runuser -l jenkins -c 'cd .ssh'
sudo runuser -l jenkins -c 'touch .ssh/authorized_keys'
sudo runuser -l jenkins -c 'echo "<enter private keys here> > ~/.ssh/authorized_keys'
sudo runuser -l jenkins -c 'chmod 600 .ssh/authorized_keys'

